pipeline:
  identifier: Build_archsmn18_web_index_sample_harness_1755774781298
  name: Build web-index-sample-harness
  orgIdentifier: default
  projectIdentifier: webpagedeployment
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: archsmn18/web-index-sample-harness
  stages:
    - stage:
        identifier: build
        name: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  name: Install Apache
                  identifier: install_apache
                  type: Run
                  spec:
                    shell: Sh
                    command: |
                      apt-get update -y
                      apt-get install -y apache2
              - step:
                  name: Copy index.html
                  identifier: copy_index
                  type: Run
                  spec:
                    shell: Sh
                    command: |
                      cp index.html /var/www/html/index.html
                      echo "Deployment done!"
              - step:
                  name: Start Apache
                  identifier: start_apache
                  type: Run
                  spec:
                    shell: Sh
                    command: |
                      service apache2 start
                      echo "Apache started. Testing..."
                      curl http://localhost/
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
